[package]
name = "rust-practice"
version = "0.1.0"
authors = ["Ben <ben@instaclustr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.5", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"]}
num_enum = "0.4.2"
bytes = "0.5.*"
futures = "0.3.1"
futures-core = "0.3.1"
config = "0.9"
serde = "1.0.104"
chrono = "0.4.6"
indexmap = "1.3.1"

# Parsers
sqlparser = "0.5.0"

#Observability
metrics = "0.12.1"


# Sink deps
redis = {version = "0.15.1", features = ["tokio-rt-core"]}
cdrs = { version = "2" }
# elasticsearch = "7.6.0-alpha.1"


[patch.crates-io]
cdrs = { path = "/Users/ben/git/cdrs", branch="release/2.2.3"}

