[package]
name = "rust-practice"
version = "0.1.0"
authors = ["Ben <ben@instaclustr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["full", "macros"] }
tokio-util = { version = "0.3.1", features = ["codec"]}
num_enum = "0.4.2"
bytes = "0.5.*"
futures = "0.3.1"
futures-core = "0.3.1"
config = "0.9"
chrono = {version = "0.4.10",  features = ["serde"]}
indexmap = "1.3.1"
async-trait = "0.1.30"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
byteorder = "1.3.2"

# Parsers
sqlparser = "0.5.0"

#Observability
metrics = "0.12.1"


# Sink deps
redis = {version = "0.15.1", features = ["tokio-rt-core"]}
cdrs = { version = "2" }
cassandra-proto = { path = "/Users/ben/git/cassandra-proto", features = ["v4"]}
rdkafka = { version = "0.23", features = ["cmake-build"] }
# elasticsearch = "7.6.0-alpha.1"

#test deps
hex-literal = "0.2.1"


[patch.crates-io]
cdrs = { path = "/Users/ben/git/cdrs", branch="release/2.2.3"}

