[package]
name = "rust-practice"
version = "0.1.0"
authors = ["Ben <ben@instaclustr.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["full", "macros"] }
tokio-util = { version = "0.3.1", features = ["codec"]}
bytes = "0.5.*"
futures = "0.3.1"
futures-core = "0.3.1"
chrono = {version = "0.4.10",  features = ["serde"]}
async-trait = "0.1.30"
byteorder = "1.3.2"
clap = "3.0.0-beta.1"
tracing = "0.1.15"
tracing-subscriber = "0.2.5"

# Error handling
thiserror = "1.0"
anyhow = "1.0.31"

# Parsers
sqlparser = "0.5.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

#Observability
metrics = "0.12.1"

# Transform dependencies
redis = {version = "0.15.1", features = ["tokio-rt-core"]}
redis-protocol = { path = "/Users/ben/git/redis-protocol.rs" }
#cdrs = { version = "2" }
cassandra-proto = { path = "/Users/ben/git/cassandra-proto", features = ["v4"]}
rdkafka = { version = "0.23", features = ["cmake-build"] }

#test deps
hex-literal = "0.2.1"

#python
pyo3 = "0.10.1"

#lua
rlua = "0.17.0"
rlua_serde = "0.4"

#Crypto
sodiumoxide = "0.2.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "chain_benches"
harness = false