[package]
name = "shotover-proxy"
version = "0.0.19"
authors = ["Ben <ben@instaclustr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.1", features = ["full", "macros"] }
tokio-util = { version = "0.6.0", features = ["codec"]}
tokio-stream = "0.1.1"
bytes = "1.0.0"
futures = "0.3.5"
bytes = "0.5.*"
futures = "0.3.9"
#futures = { path = "/home/ben/git/futures-rs/futures" }
futures-core = "0.3.1"
chrono = {version = "0.4.10",  features = ["serde"]}
async-trait = "0.1.30"
byteorder = "1.3.2"
clap = "3.0.0-beta.1"
derivative = "2.1.1"
evmap = {version = "11.0.0-alpha.7"}
itertools = "0.9.0"
rand = "0.7.3"
rand_distr = "0.2.2"
cached = "0.16.0"
pin-project = "1.0.1"
pin-project-lite = "0.2"



# Error handling
thiserror = "1.0"
anyhow = "1.0.31"

# Parsers
sqlparser = "= 0.5.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
bincode = "1.3.1"

#Observability
metrics = "0.12.1"
metrics-core = "0.5.2"
metrics-runtime = "0.13.1"
tracing = { version = "0.1.15", features = ["release_max_level_info"]}
tracing-subscriber = { version="0.2.11", features = ["env-filter"]}
tracing-futures = "0.2.4"
tracing-log = { version = "0.1.1", features = ["env_logger"] }
tracing-appender = "0.1.1"
hyper = { version = "0.14.2", features = ["server"] }


# Transform dependencies
#redis = {version = "0.15.1", features = ["tokio-rt-core", "cluster"]}
redis = {git = "https://github.com/benbromhead/redis-rs", branch = "parra_support", features = ["tokio-rt-core", "cluster"]}
#redis = {path = "/home/ben/git/redis-rs", features = ["tokio-rt-core", "cluster"]}
#redis-protocol = { path = "/home/ben/git/redis-protocol.rs"}
redis-protocol = { git = "https://github.com/benbromhead/redis-protocol.rs", branch = "remove-parser" }
#cdrs = { version = "2" }
#cassandra-proto = { path = "/home/ben/git/cassandra-proto", features = ["v4"]}
cassandra-proto = { git = "https://github.com/benbromhead/cassandra-proto", branch = "move-to-bytes", features = ["v4"]}
rdkafka = { version = "0.24", features = ["cmake-build"] }
crc16 = { version = "0.4.0"}

#test deps
hex-literal = "0.2.1"

#lua
mlua = { version = "0.4.1", features = ["async","send", "vendored","lua53"] }
mlua_serde = { version = "0.5", features = ["lua53"] }

#wasm
wasmer-runtime = "0.17.1"
#wasmer-runtime = "0.13.1"

#Crypto
sodiumoxide = "0.2.5"
rusoto_kms = "0.46.0"
rusoto_signature = "0.46.0"

[dev-dependencies]
criterion = "0.3"
#proptest = "0.10.0"
lazy_static = "1.4.0"
ctrlc = "3.1.6"


[[bench]]
name = "redis_benches"
harness = false

# https://deterministic.space/high-performance-rust.html
[profile.release]
lto = "fat"
codegen-units = 1
#debug = true

# Patches
[patch.crates-io]
cached = { git = "https://github.com/drwilco/cached", branch = "cloneless-result" }
