---
sources:
  redis_prod:
    Redis:
      batch_size_hint: 1000
      listen_addr: "127.0.0.1:6379"
      connection_limit: 1000
      hard_connection_limit: false
chain_config:
  redis_chain:
    - PoolConnections:
        name: "RedisCluster-subchain"
        parallelism: 512
        chain:
          - RedisCluster:
              first_contact_points: [ "127.0.0.1:2220", "127.0.0.1:2221", "127.0.0.1:2222", "127.0.0.1:2223", "127.0.0.1:2224", "127.0.0.1:2225" ]
named_topics:
  testtopic : 5
source_to_chain_mapping:
  redis_prod: redis_chain