---
sources:
  redis_prod:
    Redis:
      batch_max_size: 10
      listen_addr: "127.0.0.1:6379"
chain_config:
  redis_chain:
    - RedisCluster:
        first_contact_points: ["redis://127.0.0.1:2230/", "redis://127.0.0.1:2231/", "redis://127.0.0.1:2232/", "redis://127.0.0.1:2233/", "redis://127.0.0.1:2234/", "redis://127.0.0.1:2235/"]
named_topics:
  - testtopic
source_to_chain_mapping:
  redis_prod: redis_chain