# This example will replicate all commands to the DR datacenter on a best effort basis
---
sources:
  redis_dr:
    Mpsc:
      topic_name: redis-dr-tee
  redis_prod:
    Redis:
      batch_size_hint: 1000
      listen_addr: "0.0.0.0:6378"
      connection_limit: 3000000
chain_config:
  redis_dr_chain:
    - PoolConnections:
        name: "RedisCluster-DR-subchain"
        parallelism: 512
        chain:
          - RedisCluster:
              first_contact_points: [ "redis://107.20.71.3/", "redis://34.207.20.215/", "redis://34.225.18.239/" ]
  redis_chain:
    - MPSCTee:
        topic_name: redis-dr-tee
        behavior: IGNORE
    - PoolConnections:
        name: "RedisCluster-Main-subchain"
        parallelism: 512
        chain:
          - RedisCluster:
              first_contact_points: [ "redis://3.209.120.59/", "redis://107.22.193.71/", "redis://52.71.156.167/" ]
named_topics:
  testtopic: 5
  redis-dr-tee: 5
source_to_chain_mapping:
  redis_prod: redis_chain
  redis_dr: redis_dr_chain