# This example will replicate all commands to the DR datacenter on a best effort basis
---
sources:
  redis_batch:
    Mpsc:
      topic_name: redis-batch-tee
      coalesce_behavior:
        COUNT: 1000
  redis_dr:
    Mpsc:
      topic_name: redis-dr-tee
  redis_prod:
    Redis:
      batch_size_hint: 100
      listen_addr: "127.0.0.1:6379"
      connection_limit: 3000000
chain_config:
  redis-batch-chain:
    - QueryTypeFilter:
        filter: Read
    - MPSCForwarder:
        topic_name: redis-dr-tee
        async_mode: false
  redis_dr_chain:
    - PoolConnections:
        name: "RedisCluster-DR-subchain"
        parallelism: 256
        chain:
          - RedisCluster:
              first_contact_points: [ "redis://127.0.0.1:2120/", "redis://127.0.0.1:2121/", "redis://127.0.0.1:2122/", "redis://127.0.0.1:2123/", "redis://127.0.0.1:2124/", "redis://127.0.0.1:2125/" ]
  redis_chain:
    - MPSCTee:
        topic_name: redis-batch-tee
        behavior: IGNORE
        timeout_micros: 40
    - PoolConnections:
        name: "RedisCluster-Main-subchain"
        parallelism: 512
        chain:
          - RedisCluster:
              first_contact_points: [ "redis://127.0.0.1:2220/", "redis://127.0.0.1:2221/", "redis://127.0.0.1:2222/", "redis://127.0.0.1:2223/", "redis://127.0.0.1:2224/", "redis://127.0.0.1:2225/" ]
named_topics:
  redis-dr-tee : 5000
  redis-batch-tee : 10000
source_to_chain_mapping:
  redis_prod: redis_chain
  redis_dr: redis_dr_chain
  redis_batch: redis-batch-chain