# This example will replicate all commands to the DR datacenter on a best effort basis
---
sources:
  redis_prod:
    Redis:
      batch_size_hint: 4
      listen_addr: "127.0.0.1:6379"
      connection_limit: 3000000
chain_config:
  redis_chain:
    - MPSCTee:
        behavior: IGNORE
#        timeout_micros: 1000
        buffer_size: 10000
        chain:
          - QueryTypeFilter:
              filter: Read
          - Coalesce:
              max_behavior:
                COUNT: 2000
          - MPSCForwarder:
              buffer_size: 100
              async_mode: true
              timeout_micros: 10000
              chain:
                - PoolConnections:
                    name: "RedisCluster-DR-subchain"
                    parallelism: 256
                    chain:
                      - RedisCluster:
                          first_contact_points: [ "redis://127.0.0.1:2120/", "redis://127.0.0.1:2121/", "redis://127.0.0.1:2122/", "redis://127.0.0.1:2123/", "redis://127.0.0.1:2124/", "redis://127.0.0.1:2125/" ]

    - PoolConnections:
        name: "RedisCluster-Main-subchain"
        parallelism: 512
        chain:
          - RedisCluster:
              first_contact_points: [ "redis://127.0.0.1:2220/", "redis://127.0.0.1:2221/", "redis://127.0.0.1:2222/", "redis://127.0.0.1:2223/", "redis://127.0.0.1:2224/", "redis://127.0.0.1:2225/" ]
named_topics:
  example: 10
source_to_chain_mapping:
  redis_prod: redis_chain