---
sources:
  redis_prod:
    Redis:
      batch_size_hint: 1
      listen_addr: "127.0.0.1:6379"
chain_config:
  redis_chain:
    - SequentialMap:
        first_contact_points: ["172.18.0.7:6379"]
named_topics:
  testtopic: 5
source_to_chain_mapping:
  redis_prod: redis_chain