---
sources:
  redis_prod:
    Redis:
      listen_addr: "127.0.0.1:6379"
chain_config:
  redis_chain:
    - ConsistentScatter:
        write_consistency: 1
        read_consistency: 1
        route_map:
          one:
            - RedisTimestampTagger
            - RedisDestination:
                remote_address: "127.0.0.1:3331"
#          two:
#            - RedisTimestampTagger
#            - RedisDestination:
#                remote_address: "127.0.0.1:3332"
#          three:
#            - RedisTimestampTagger
#            - RedisDestination:
#                remote_address: "127.0.0.1:3333"
named_topics:
  - testtopic
source_to_chain_mapping:
  redis_prod: redis_chain