---
sources:
  redis_prod:
    Redis:
      listen_addr: "127.0.0.1:6379"
chain_config:
  redis_chain:
    - ResponseResolver: []
    - ConsistentScatter:
        write_consistency: 2
        read_consistency: 2
        route_map:
          one:
            - RedisDestination:
                remote_address: "127.0.0.1:1111"
          two:
            - RedisDestination:
                remote_address: "127.0.0.1:2222"
          three:
            - RedisDestination:
                remote_address: "127.0.0.1:3333"
named_topics:
  - testtopic
source_to_chain_mapping:
  redis_prod: redis_chain